services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organizer_app
    ports:
      - "3002:3000"  # Public port 80 -> internal port 3000
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
